-- ============================================================
-- 오늘로 앱 — 물리 데이터 모델 v3
-- PostgreSQL 기준
-- 전용 스키마: oneulro
-- 물리 FK 제약 있음 (app_user 참조)
-- 이 파일은 실제 운영 DB 스키마와 동일하게 유지한다.
-- 컬럼을 추가/변경할 때는 migrations/ 아래에 SQL 파일을 만들고 이 파일도 함께 갱신할 것.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS oneulro;

SET search_path TO oneulro;

-- ------------------------------------------------------------

CREATE TABLE app_user (
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_provider     VARCHAR(20) NOT NULL,
    social_id           VARCHAR(255) NOT NULL,
    nickname            VARCHAR(50) NOT NULL,
    profile_image_url   TEXT,
    refresh_token       VARCHAR(500),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ,

    UNIQUE (social_provider, social_id)
);


CREATE TABLE search_preset (
    preset_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES app_user(user_id),
    name                    VARCHAR(100),
    departure_station       VARCHAR(100) NOT NULL,
    travel_days             INTEGER,
    companion_type          VARCHAR(20),
    budget_min              INTEGER,
    budget_max              INTEGER,
    pet_mode                VARCHAR(20),
    theme_tags              JSONB,
    natural_language_memo   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE course (
    course_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES app_user(user_id),
    preset_id               BIGINT REFERENCES search_preset(preset_id),

    title                   VARCHAR(200) NOT NULL,
    alias                   VARCHAR(100),
    departure_station       VARCHAR(100) NOT NULL,

    start_date              DATE,
    end_date                DATE,
    total_days              INTEGER,

    budget_min              INTEGER,
    budget_max              INTEGER,

    recommendation_reason   TEXT,

    visibility              VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    view_count               BIGINT NOT NULL DEFAULT 0,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMPTZ
);


CREATE TABLE course_stop (
    stop_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id           BIGINT NOT NULL REFERENCES course(course_id),

    day_number          INTEGER NOT NULL,
    sequence            INTEGER NOT NULL,

    station_name        VARCHAR(100) NOT NULL,

    lat numeric(10, 7) NULL,
    lng numeric(10, 7) NULL,

    -- S-05 역 카드(이미지/혼잡도/혜택역) 지원 (migrations/0001)
    image_url           TEXT,
    congestion_score    INTEGER,
    is_benefit_station  BOOLEAN NOT NULL DEFAULT FALSE,

    train_type          VARCHAR(20),
    train_number        VARCHAR(50),
    seat_class          VARCHAR(20),

    arrive_at           TIMESTAMPTZ,
    depart_at           TIMESTAMPTZ,

    stay_minutes        INTEGER,
    travel_minutes      INTEGER,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (course_id, day_number, sequence)
);


CREATE TABLE place (
    place_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stop_id             BIGINT NOT NULL REFERENCES course_stop(stop_id),

    name                VARCHAR(200) NOT NULL,
    category            VARCHAR(50),
    address             VARCHAR(200),

    lat                 NUMERIC(10, 7),
    lng                 NUMERIC(10, 7),

    sequence            INTEGER,

    image_url           TEXT,
    opening_hours       VARCHAR(200),

    walk_minutes        INTEGER,
    congestion_score    INTEGER,
    weather_summary     VARCHAR(100),

    pet_allowed         BOOLEAN NOT NULL DEFAULT FALSE,
    indoor_yn           BOOLEAN NOT NULL DEFAULT FALSE,
    free_yn             BOOLEAN NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (stop_id, sequence)
);


CREATE TABLE course_rating (
    rating_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES app_user(user_id),
    course_id           BIGINT NOT NULL REFERENCES course(course_id),

    rating              SMALLINT NOT NULL,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, course_id)
);


CREATE TABLE course_like (
    user_id             BIGINT NOT NULL REFERENCES app_user(user_id),
    course_id           BIGINT NOT NULL REFERENCES course(course_id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, course_id)
);


CREATE TABLE course_bookmark (
    user_id             BIGINT NOT NULL REFERENCES app_user(user_id),
    course_id           BIGINT NOT NULL REFERENCES course(course_id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, course_id)
);


CREATE TABLE course_member (
    course_member_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id           BIGINT NOT NULL REFERENCES course(course_id),
    user_id             BIGINT NOT NULL REFERENCES app_user(user_id),

    status              VARCHAR(20) NOT NULL DEFAULT 'INVITED',

    joined_at           TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (course_id, user_id)
);


CREATE TABLE share_link (
    link_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id           BIGINT NOT NULL REFERENCES course(course_id),
    created_by          BIGINT NOT NULL REFERENCES app_user(user_id),

    token               VARCHAR(100) NOT NULL UNIQUE,

    expires_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at          TIMESTAMPTZ
);
