apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "oneulro"
  DB_USER: "oneulro"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "oneulro"
  KAKAO_REDIRECT_URI: "https://161.33.31.75.nip.io/login/kakao/callback"
